export const getPastelColor = (title: string = "") => {
  const colors: { [key: string]: string } = {
    A: "bg-pink-50",
    B: "bg-blue-50",
    C: "bg-green-50",
    D: "bg-purple-50",
    E: "bg-yellow-50",
    F: "bg-orange-50",
    G: "bg-red-50",
    H: "bg-indigo-50",
    I: "bg-pink-50",
    J: "bg-blue-50",
    K: "bg-green-50",
    L: "bg-purple-50",
    M: "bg-yellow-50",
    N: "bg-orange-50",
    O: "bg-red-50",
    P: "bg-indigo-50",
    Q: "bg-pink-50",
    R: "bg-blue-50",
    S: "bg-green-50",
    T: "bg-purple-50",
    U: "bg-yellow-50",
    V: "bg-orange-50",
    W: "bg-red-50",
    X: "bg-indigo-50",
    Y: "bg-pink-50",
    Z: "bg-blue-50",
    "1": "bg-teal-50",
    "2": "bg-cyan-50",
    "3": "bg-lime-50",
    "4": "bg-amber-50",
    "5": "bg-emerald-50",
    "6": "bg-fuchsia-50",
    "7": "bg-rose-50",
    "8": "bg-sky-50",
    "9": "bg-violet-50",
    "0": "bg-slate-50",
  };
  const firstChar = title.charAt(0).toUpperCase();
  return colors[firstChar] || "bg-gray-50";
};

export const getFishImage = (title: string = "") => {
  const fishMap: { [key: string]: string } = {
    A: "fish1.svg",
    B: "fish2.svg",
    C: "fish3.svg",
    D: "fish4.svg",
    E: "fish5.svg",
    F: "fish6.svg",
    G: "fish7.svg",
    H: "fish8.svg",
    I: "fish9.svg",
    J: "fish10.svg",
    K: "fish11.svg",
    L: "fish12.svg",
    M: "fish13.svg",
    N: "fish14.svg",
    O: "fish15.svg",
    P: "fish16.svg",
    Q: "fish17.svg",
    R: "fish18.svg",
    S: "fish19.svg",
    T: "fish20.svg",
    U: "fish1.svg",
    V: "fish2.svg",
    W: "fish3.svg",
    X: "fish4.svg",
    Y: "fish5.svg",
    Z: "fish6.svg",
    "1": "fish7.svg",
    "2": "fish8.svg",
    "3": "fish9.svg",
    "4": "fish10.svg",
    "5": "fish11.svg",
    "6": "fish12.svg",
    "7": "fish13.svg",
    "8": "fish14.svg",
    "9": "fish15.svg",
    "0": "fish16.svg",
  };
  const firstChar = title.charAt(0).toUpperCase();
  return fishMap[firstChar] || "fish1.svg";
};

